const userActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_LOGIN_START: "GOOGLE_LOGIN_START",
  EMAIL_LOGIN_START: "EMAIL_LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
};

export default userActionTypes;